flow mode implementation
swdotcom/swdc-atom pull request #65
Opened 2021-01-23 23:26 UTC by xavluiz

2021-01-24 18:56 UTC, brettmstevens7 commented on lib/managers/FlowManager.js
> +    screenInFlowState = true;
Why is this one true?

2021-01-24 18:58 UTC, brettmstevens7 commented on lib/managers/SlackManager.js
> +    if (showSuccessNotification) {
Don't think we need to show notifications on enabling/disabling flow mode.

2021-01-24 19:02 UTC, brettmstevens7 requested changes
Couple suggested changes around Enable Flow Mode

2021-01-25 04:48 UTC, xavluiz commented on lib/managers/FlowManager.js
> +    screenInFlowState = true;
which one? zen? it was just there in case I found out if atom has zen mode or not. i'll take it out

2021-01-25 04:48 UTC, xavluiz commented on lib/managers/SlackManager.js
> +    if (showSuccessNotification) {
ok

2021-01-25 04:49 UTC, xavluiz commented on lib/managers/SlackManager.js
> +    if (showSuccessNotification) {
oh, its not for flow mode

2021-01-26 19:06 UTC, merged